name: Test GitHub Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - id: extract-metadata
        uses: ./
      - name: Log output of the previous step
        run: |
          echo "This is the output of the previous step:"   
          echo ${{ steps.extract-metadata.outputs.metadata }}